language: go

go:
  - 1.6
  - tip

# installing godep manually: https://github.com/travis-ci/travis-ci/issues/5702
install:
  - go get -t github.com/tools/godep
  - godep restore
  - go get -t -v ./...

env:
  global:
    - GO15VENDOREXPERIMENT=1

before_script:
  - go install ./...
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  # disabled checks fail on tip
  - gometalinter --deadline 60s --cyclo-over 12 -D structcheck -D aligncheck ./...
