#
#   Author: Rohith (gambol99@gmail.com)
#   Date: 2015-02-17 17:11:18 +0000 (Tue, 17 Feb 2015)
#
#  vim:ts=2:sw=2:et
#
language: go
go:
  - 1.3.3
  - 1.4
  - tip
install:
  - go get
  - go build
  - go get gopkg.in/yaml.v2
  - go test -v
